version: "3.9"

services:
  rabbitmq:
    image: "rabbitmq:3"
    hostname: "rabbitmq"
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    
  fastapi:
      build: .
      ports:
        - "80:80"
        - "5555:5555"
      depends_on:
        - rabbitmq
      volumes:
      - "./app:/app"